### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by szsliaiu** [remember-5/eladmin-plus#4]
Cannot deserialize value of type `int` from String "${REDIS_DB}": not a valid `int` value

**Comment by remember-5** [comment]
> Cannot deserialize value of type `int` from String "${REDIS_DB}": not a valid `int` value

使用环境变量启动，查看README中，变量值

**Comment by szsliaiu** [comment]
设置了环境变量但是minio那块报错，一定要配置minio才能启动吗

**Comment by remember-5** [comment]
> 置了环境变量但是minio那块报错，一定要配置minio才能启动

minio可以单独配置开关
